fun main() {
//    val day = Day()
//    val day = Day2()
//    val day = Day3()
//    val day = Day4()
//    val day = Day5()
//    val day = Day6()
//    val day = Day7()
//    val day = Day8()
//    val day = Day9()
//    val day = Day10()
//    val day = Day11()
//    val day = Day12()
    val day = Day13()
//    println(day.getAnswer1())
    println(day.getAnswer2())
}